# Generated by Django 4.2 on 2023-07-09 10:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=main.models.dynamic_path,
                        validators=[main.models.validate_file_extension],
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
